---
- name: install apchae server and packages
  hosts: webserver
  become: yes
  tasks:
    - name: File the execution when the distibution is not ubuntu ans centos
      fail:
        msg: "This playbook will work only on  ubuntu instance. Support for other os will be add soon"
      when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "CentOS"

    - name: Install apache
      package:
        name: "{{ apache_package }}"
        state: present
      notify:
        - log installed apache server

    - name: Install php packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"

    - name: copy the php page
      copy:
        dest: "{{ info_php_path }}"
        src: "info.php"
      notify:
        - info page copied

    - name: ensure the service is running
      service:
        name: "{{ apache_package }}"
        enabled: yes
        state: started
      notify:
        - restart apache

  handlers:
    - name: log installed apache server
      debug:
        msg: "apache server installed using package {{ apache_package }}"
    - name: info page copied
      debug:
        msg: "info page copied into {{ info_php_path }}"
    - name: restart apache
      service:
        name: "{{ apache_package }}"
        state: restarted

