---
- name: Deploy spring petclinic as linux servier
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic
    app_download_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file_name: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    app_username: springbootuser
  tasks:
    - name: update ubuntu packages and install java
      apt:
       name: "{{ java_package }}"
       update_cache: yes
       state: present
    - name: Create spring petclinic directory
      file:
        path: "{{ app_dir }}"
        state: directory
    - name: download spring petclinic
      get_url:
        url: "{{ app_download_url }}"
        dest: "{{ app_file_name }}"
    - name: create springboot user
      user:
        name: "{{ app_username }}"
        password: "{{ app_username }}"
        state: present
    - name: change ownership of jar file
      file:
        path: "{{ app_filename }}"
        owner: "{{ app_username}}"
        mode: '500'
        state: file
    - name: copy the spring petclinic service file
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: enable and start spring petclinic
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started
